(keyboard-translate ?\C-h ?\C-?)
(define-key global-map (kbd "C-c l") 'toggle-truncate-lines)
(define-key global-map (kbd "C-c C-s") 'magit-status)
(define-key global-map (kbd "C-t") 'other-window)
(define-key global-map (kbd "C-a") 'seq-home)
(define-key global-map (kbd "C-e") 'seq-end)
(define-key global-map (kbd "C-m") 'newline-and-indent)
(define-key global-map (kbd "C-c C-j") 'skk-mode)

(global-set-key (kbd "C-@") 'er/expand-region)
(global-set-key (kbd "C-c C-f") 'my/helm-files)
(global-set-key (kbd "C-M-@") 'er/contract-region)
(global-set-key (kbd "M-%") 'anzu-query-replace)
(global-set-key (kbd "C-M-%") 'anzu-query-replace-regexp)
(provide 'set-global-keybind)
