(source gnu)
(source melpa)
(source marmalade)

(depends-on "helm")

;; Setup
(depends-on "init-loader")

;; prog suport
(depends-on "flymake")
(depends-on "flymake-cursor")
(depends-on "flycheck")
(depends-on "flycheck-color-mode-line")
(depends-on "ac-helm")
(depends-on "magit")
(depends-on "git-gutter")
(depends-on "sequential-command")
(depends-on "foreign-regexp")
(depends-on "anzu")
(depends-on "expand-region")
(depends-on "auto-complete")
;;(depends-on "ace-jump")

;; html
(depends-on "slim-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")

;; prog modes
(depends-on "ac-slime")
(depends-on "slime")
(depends-on "markdown-mode")
(depends-on "web-mode")
(depends-on "yaml-mode")

; ruby
(depends-on "rubocop")
(depends-on "rbenv")
(depends-on "enh-ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-electric")
(depends-on "ruby-end")

;; prog completion
(depends-on "yasnippet")
