(source gnu)
(source melpa)
(source marmalade)

(depends-on "helm")

;; prog suport
(depends-on "flycheck")
(depends-on "flycheck-color-mode-line")
(depends-on "ac-helm")
(depends-on "magit")
(depends-on "git-gutter")
(depends-on "sequential-command")
(depends-on "foreign-regexp")
(depends-on "anzu")

;; prog modes
(depends-on "markdown-mode")
(depends-on "web-mode")
(depends-on "yaml-mode")

(depends-on "rubocop")
(depends-on "rbenv")
(depends-on "enh-ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-electric")
(depends-on "ruby-end")

;; prog completion
(depends-on "yasnippet")
