(source gnu)
(source melpa)
(source marmalade)

(depends-on "helm")

;; prog suport
(depends-on "flycheck")
(depends-on "flycheck-color-mode-line")

;; prog modes
(depends-on "rubocop")
(depends-on "rbenv")
(depends-on "enh-ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-electric")
(depends-on "ruby-end")

;; prog completion
(depends-on "yasnippet")
